### ISSUE TITLE
How do I make text go to the next line?

### ISSUE THREAD

**Issue by pdyatlov** [Fribur/TextMeshDOTS#5]
Hi, thanks for coming up with this repo!

I'm using it right now for my project but can't figure out how to make my text switch to the next line.
Using \n won't work and it's displayed as a sequence of characters - "\\" and "n" correspondingly. 

I'd appreciate your input on this matter

**Comment by Fribur** [comment]
Hi, if you want to force a new line using the text input field in the editor, just press enter. Via script: calliString.Append("Te\nst 123");
